test:
    resource: "@TestBundle/Resources/config/routing.yml"
    prefix:   /

animal:
    resource: "@AnimalBundle/Resources/config/routing.yml"
    prefix:   /

app:
    resource: "@AppBundle/Controller/"
    type:     annotation

genus_get_notes:
    path:     /genus/{genusName}/notes
    defaults: { _controller: TestBundle:Default:getNotes }